// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/collections": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/strategies": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/help": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/auth/*" | "/app" | "/app/collections" | "/app/additional" | "/app/strategies" | "/app/analytics" | "/app/settings" | "/app/billing" | "/app/help";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/collections" | "/app/additional" | "/app/strategies" | "/app/analytics" | "/app/settings" | "/app/billing" | "/app/help";
  };
  "routes/app.collections.jsx": {
    id: "routes/app.collections";
    page: "/app/collections";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.strategies.jsx": {
    id: "routes/app.strategies";
    page: "/app/strategies";
  };
  "routes/app.analytics.jsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.billing.jsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.help.jsx": {
    id: "routes/app.help";
    page: "/app/help";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.collections": typeof import("./app/routes/app.collections.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.strategies": typeof import("./app/routes/app.strategies.jsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.help": typeof import("./app/routes/app.help.jsx");
};